#!/bin/bash
# Generates a documentation markdown file for util.sh
# It documents all functions by grabbing the function names
# and their documentation comments above the their header.

# shellcheck disable=2155

# shellcheck source=./util.sh
source "./util.sh"

UTIL_SH="${ROOT}/util.sh"

check_file "$UTIL_SH"
check "pcregrep"
check "sed"

function gen_docs {
    local doc_groups
    # argument used as nameref
    get_function_headers_with_docs doc_groups

    local markdown_sections=()
    local doc_group
    local doc_lines
    local doc_code
    local doc_text
    local function_name
    local variable_name # TODO

    for doc_group in "${doc_groups[@]}"; do
        mapfile -t doc_lines <<< "$doc_group"
        # TODO: The substitution here starts at :1 which is because
        #       the docs seem to always start with a new line;
        #       this is a hacky "solution".
        doc_text="$(
            join_by $'  \n' \
                "${doc_lines[@]:1:${#doc_lines[@]}-2}" \
                | sed 's/^#\s\+//g'
        )"
        doc_code="${doc_lines[-1]}"
        if [ -n "$doc_code" ] \
            && [[ $doc_code =~ ^\s*function ]]
        then
            # Is a function header
            # TODO: This only parses the function name when using this syntax:
            #           function my_func
            function_name="$(
                echo "$doc_code" \
                        | sed -En 's/^\s*function\s+(\w+)\s+.*$/\1/p'
            )"
            markdown_sections+=( \
                $'### [`function '"${function_name}"$'`](#function-'"${function_name}"')
'"${doc_text}" \
            )
        fi
    done

    local markdown="$( join_by $'\n\n---\n\n' "${markdown_sections[@]}" )"
    echo "${markdown}"
}

function get_function_headers_with_docs {
    # https://stackoverflow.com/a/49971213
    local -n return_doc_groups="$1"
    local lftmp="<NEWLINE>"

    mapfile -t return_doc_groups < <(
        pcregrep -MA1 \
            '(^\s*#[^\n]+$)+' \
            "$UTIL_SH" \
            | sed ':a;N;$!ba;s/\n/'"${lftmp}"'/g' \
            | sed 's/'"${lftmp}"'--'"${lftmp}"'/\n/g'
            # https://stackoverflow.com/a/1252191
    )

    local i
    for (( i = 0; i < ${#return_doc_groups[@]}; i++ )); do
        return_doc_groups[i]="${doc_groups[i]//"$lftmp"/$'\n'}"
    done
}

gen_docs "$@"
